services:
  notifer:
    container_name: notifer
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - 8026:8026
    volumes:
      - app_data:/app/data
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - default

  postgres:
    container_name: postgres
    image: postgres:17.2-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped
    networks:
      - default

volumes:
  app_data:
  postgres_data:
