services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: fastapi_api
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - redis
    networks:
      - backend
  
  redis:
    image: redis:7-alpine
    container_name: fastapi_redis
    ports:
      - "6379:6379"
    networks:
      - backend
        
networks:
  backend:
