# this file is used for production

services:
  traefik:
    image: traefik:v3.1
    command:
      - "--api=true"
      - "--api.dashboard=true"
      - "--api.insecure=false"
      
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      
      - "--entrypoints.web.address=:8080"
      - "--entryPoints.websecure.address=:8443"
      
      - "--certificatesresolvers.le.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.le.acme.dnschallenge=true"
      - "--certificatesresolvers.le.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.le.acme.email=admin@emilpopovic.me"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.notifer.emilpopovic.me`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=le"
      - "traefik.http.middlewares.auth-dashboard.basicauth.userfile=/run/secrets/dashboard-auth"
      - "traefik.http.routers.dashboard.middlewares=auth-dashboard"
    secrets:
      - cloudflare-api-token
      - dashboard-auth
    environment:
      - CF_DNS_API_TOKEN_FILE=/run/secrets/cloudflare-api-token
      - DASHBOARD_AUTH_FILE=/run/secrets/dashboard-auth
    ports:
      - mode: host
        protocol: tcp
        published: 8080
        target: 8080
      - mode: host
        protocol: tcp
        published: 8443
        target: 8443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_cert:/letsencrypt

  api:
    image: emilpopovic/notifer_api:${GIT_COMMIT_HASH:-latest}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.api.loadbalancer.server.port=8000"
      - "traefik.http.routers.api.rule=Host(`notifer.emilpopovic.me`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=le"
    secrets:
      - db-password
      - jwt-key
      - resend-api-key
      - confirmation-password
    environment:
      - API_URL=https://notifer.emilpopovic.me
      - POSTGRES_HOST=aws-0-eu-central-1.pooler.supabase.com
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - POSTGRES_USER=postgres.zjslydzomixtnrauxppc
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_SSLMODE=disable
      - SECRET_KEY_FILE=/run/secrets/jwt-key
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - CONFIRMATION_USERNAME=confirm@notifer.emilpopovic.me
      - RESEND_API_KEY_FILE=/run/secrets/resend-api-key
      - CONFIRMATION_FALLBACK_USERNAME=notifer.updates@gmail.com
      - CONFIRMATION_PASSWORD_FILE=/run/secrets/confirmation-password
    deploy:
      replicas: 3
      update_config:
        order: start-first
    depends_on:
      - redis
      - email_worker

  calendar_worker:
    image: emilpopovic/notifer_calendar_worker:${GIT_COMMIT_HASH:-latest}
    secrets:
      - db-password
      - jwt-key
      - resend-api-key
      - update-password
    environment:
      - API_PORT=8000
      - API_URL=https://notifer.emilpopovic.me
      - POSTGRES_HOST=aws-0-eu-central-1.pooler.supabase.com
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - POSTGRES_USER=postgres.zjslydzomixtnrauxppc
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_SSLMODE=disable
      - SECRET_KEY_FILE=/run/secrets/jwt-key
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - UPDATE_USERNAME=updates@notifer.emilpopovic.me
      - RESEND_API_KEY_FILE=/run/secrets/resend-api-key
      - UPDATE_FALLBACK_USERNAME=notifer.updates@gmail.com
      - UPDATE_PASSWORD_FILE=/run/secrets/update-password
    depends_on:
      - redis
      - email_worker
      - api
  
  email_worker:
    image: emilpopovic/notifer_email_worker:${GIT_COMMIT_HASH:-latest}
    deploy:
      replicas: 5
    command: rq worker email --url redis://redis:6379/0
    secrets:
      - db-password
    environment:
      - POSTGRES_HOST=aws-0-eu-central-1.pooler.supabase.com
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - POSTGRES_USER=postgres.zjslydzomixtnrauxppc
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_SSLMODE=disable
    depends_on:
      - redis
  
  redis:
    image: redis:alpine
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  traefik_cert:
    
secrets:
  db-password:
    external: true
  jwt-key:
    external: true
  confirmation-password:
    external: true
  update-password:
    external: true
  resend-api-key:
    external: true
  cloudflare-api-token:
    external: true
  dashboard-auth:
    external: true
