# this file is used for local development only

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./secrets/db-password.txt:/run/secrets/db-password:ro
      - ./secrets/jwt-key.txt:/run/secrets/jwt-key:ro
      - ./secrets/confirmation-password.txt:/run/secrets/confirmation-password:ro
    environment:
      - API_URL=http://localhost:8000
      - POSTGRES_HOST=aws-0-eu-central-1.pooler.supabase.com
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - POSTGRES_USER=postgres.zjslydzomixtnrauxppc
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_SSLMODE=disable
      - SECRET_KEY_FILE=/run/secrets/jwt-key
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - CONFIRMATION_USERNAME=notifer.updates@gmail.com
      - CONFIRMATION_PASSWORD_FILE=/run/secrets/confirmation-password
    depends_on:
      - redis
      - email_worker
    
  calendar_worker:
    build:
      context: .
      dockerfile: calendar_worker/Dockerfile
    volumes:
      - ./secrets/db-password.txt:/run/secrets/db-password:ro
      - ./secrets/update-password.txt:/run/secrets/update-password:ro
      - ./secrets/jwt-key.txt:/run/secrets/jwt-key:ro
    environment:
      - API_PORT=8000
      - API_URL=http://localhost:8000
      - POSTGRES_HOST=aws-0-eu-central-1.pooler.supabase.com
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - POSTGRES_USER=postgres.zjslydzomixtnrauxppc
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_SSLMODE=disable
      - SECRET_KEY_FILE=/run/secrets/jwt-key
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - UPDATE_USERNAME=notifer.updates@gmail.com
      - UPDATE_PASSWORD_FILE=/run/secrets/update-password
    depends_on:
      - redis
      - email_worker
      - api
  
  email_worker:
    build:
      context: .
      dockerfile: email_worker/Dockerfile
    command: rq worker email --url redis://redis:6379/0
    depends_on:
      - redis
  
  redis:
    image: redis:alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
