# this file is used for production

services:
  traefik:
    image: traefik:v3.1
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--certificatesresolvers.le.acme.email=admin@emilpopovic.me"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik_cert
    networks:
      - backend

  api:
    image: emilpopovic/notifer_api:${GIT_COMMIT_HASH:-latest}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.whoami.loadbalancer.port=8000"
      - "traefik.http.routers.api.rule=Host(`notifer.emilpopovic.me`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=le"
    secrets:
      - db-password
      - jwt-key
      - confirmation-password
    environment:
      - API_URL=https://notifer.emilpopovic.me
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=app
      - POSTGRES_PORT=5432
      - POSTGRES_SSLMODE=disable
      - SECRET_KEY_FILE=/run/secrets/jwt-key
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - CONFIRMATION_USERNAME=obico.updates@gmail.com
      - CONFIRMATION_PASSWORD_FILE=/run/secrets/confirmation-password
    scale: 3
    deploy:
      update_config:
        order: start-first
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
      email_worker:
        condition: service_started
    networks:
      - backend

  calendar_worker:
    image: emilpopovic/notifer_calendar_worker:${GIT_COMMIT_HASH:-LATEST}
    secrets:
      - db-password
      - update-password
      - jwt-key
    environment:
      - API_PORT=8000
      - API_URL=https://notifer.emilpopovic.me
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=app
      - POSTGRES_PORT=5432
      - POSTGRES_SSLMODE=disable
      - SECRET_KEY_FILE=/run/secrets/jwt-key
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - UPDATE_USERNAME=obico.updates@gmail.com
      - UPDATE_PASSWORD_FILE=/run/secrets/update-password
    networks:
      - backend
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
      email_worker:
        condition: service_started
      api:
        condition: service_started
  
  email_worker:
    image: emilpopovic/notifer_email_worker:${GIT_COMMIT_HASH:-LATEST}
    scale: 5
    command: rq worker email --url redis://redis:6379/0
    networks:
      - backend
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
  
  redis:
    image: redis:alpine
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
  
  db:
    image: postgres:13-alpine
    secrets:
      - db-password
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - POSTGRES_DB=app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  traefik_cert:
    
secrets:
  db-password:
    external: true
  jwt-key:
    external: true
  confirmation-password:
    external: true
  update-password:
    external: true
